version: 0.2

env:
  variables:
    GO_VERSION: 1.23.4
    S3_BUCKET: cardlambda1980
phases:
  install:
    commands:
      - yum install wget zip -y
      - wget https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz
      - tar -C /usr/local -xzf go${GO_VERSION}.linux-amd64.tar.gz
      - export PATH="/usr/local/go/bin:$PATH" && export GOPATH="$HOME/go" && export PATH="$GOPATH/bin:$PATH"
      - go get -v -u github.com/aws/aws-lambda-go
  pre_build:
    commands:
      - echo Start pre_build...
  build:
    commands:
      - echo Start build...
      - CGO_ENABLED=0 go build -o bootstrap main.go
      - zip lambda-handler.zip bootstrap
  post_build:
    commands:
      - echo Start post_build...
      - echo Uploading to S3...
      - aws s3 cp $CODEBUILD_SRC_DIR/lambda-handler.zip s3://${S3_BUCKET}/lambda-handler.zip
      - echo Done.

